# AllCops

AllCops:
  Exclude:
    - 'Rakefile'
    - 'Gemfile'
    - 'torznab-client.gemspec'
    - 'spec/spec_helper.rb'

# Metrics

Metrics/LineLength:
  Max: 120

# Style

Style/RescueStandardError:
  Enabled: false
