# AllCops

AllCops:
  Exclude:
    - 'Rakefile'
    - 'Gemfile'
    - 'torznab-client.gemspec'
    - 'spec/spec_helper.rb'

# Metrics

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 18

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

# Layout

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# Style

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RescueStandardError:
  Enabled: false
